### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Jomik** [GatoMiopia/Klipper_Z_Tramming#1]
Hey! Awesome work!
Please add a license :)

**Comment by GatoMiopia** [comment]
License added!

**Comment by Jomik** [comment]
Awesome, thanks! I did end up creating my own version, inspired by yours :)

I was about to open a PR, but realized that it is essentially a full re-implementation, the overall structure of the macro is the same though.
You can see it here
https://github.com/Jomik/klipper-z-tramming/blob/abfec19170501b87863c19f44a6c34b84161af6c/macros/z_tramming.cfg

I primarily wanted to ensure that the user could configure it without needing to modify the macro itself, to make it easy to upgrade.
That would also make it possible to manage it with Moonraker :)
